version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/.htpasswd:/etc/nginx/.htpasswd"
  web:
    hostname: web
    build:
      context: "./web"
    expose:
      - "80"
    command: /bin/sh -c "uvicorn app:api --host 0.0.0.0 --port 80"
    volumes:
      - "./web:/var/source/web"
      - "datavolume:/data"
  discord:
    hostname: discord
    build:
      context: "./discord"
    volumes:
      - "./discord:/var/source/discord"
      - "datavolume:/data"

volumes:
  datavolume: