version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      
      - cd ./web

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./web/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          working_directory: web
          command: npm install

      - save_cache:
          working_directory: web
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./web/package.json" }}

      - run: 
          working_directory: web
          command: npm run test

